<?php
/*
Information:

Session Mechanism:

Upon login (generateUserSession($data)), the user will be assigned a user token generateUserToken().  This token will last for 7 days maximum, for a month if the 'Remember me' option is ticked. 

The token generated by the user logged in will be compared against the database. If the token matches with the username assigned to it, the user will be logged in smoothly. Otherwise if the server token is removed by the user or by expiry the user will be logged out and be blocked from accessing the rest of the website and will only be limited to the login page and the index.php page which will redirect to the currently active server.

THIS SCRIPT IS CRUCIAL WHEN CONNECTING TO THE SERVER AND DATABASE. Most of the site functions will break, if not won't work at all when this script isnt called or included in every webpage.  
*/
require 'conn.ini.php';
include "../query/classes/helper.cls.php";
class userSession extends db1 {
    //set Current Date and Expiration Date (+ 7 days)
    function setSessionDate() { 
        date_default_timezone_set('Asia/Manila');
        $curr_dateSession = new DateTime; // Current date
        $exp_dateSession = new DateTime; // current date + 7 days 
        $exp_dateSession->add(DateInterval::createFromDateString("7 day"));

        // If "Remember Me" option is selected the token should expire in 30 days instead

        $dateSession = array("exp_dateSession"=> $exp_dateSession->format("Y-m-d H:i:s"), "curr_dateSession"=>  $curr_dateSession->format("Y-m-d H:i:s"));

        return $dateSession; 
    }

    // Encrypted values for Token - 16 characters long through bin2hex
    function generateUserToken() {
        $token = bin2hex(random_bytes(16));
        return $token;
    }
    
    // connect to session table, get the username of the currently active user and pass the token to that username. The token will last for 7 days (expiry_date). If the expiry date has been reached or exceeded, the token will be automatically deleted with SQL Events. 
    function setSessionToken($token, $sessionDate) {
        $tokentype = '1';
        try { 
            $sql = "INSERT INTO usersession (token, tokentype, date_set, date_expiry) VALUES (?,?,?,?)";
            $stmt = parent::conn()->prepare($sql);
            $stmt->execute(array($token, $tokentype, $sessionDate['curr_dateSession'], $sessionDate['exp_dateSession'])); 
        }
        catch(PDOException $ex){
            echo $ex;
        }          

    }

    // Retrives the session tokens from the database so it can be checked if it matches the one given by the client.
    function getSessionToken($token) {
        try { 
            $sql = " SELECT * FROM usersession WHERE token = ? ";
            $stmt = parent::conn()->prepare($sql);
            $stmt->execute(array($token)); 
            $tokenData = $stmt->fetch(PDO::FETCH_ASSOC);
            $tokenMatchVal = $stmt->rowCount();
            $sessionTokenData = array ('tokenData'=>$tokenData,'tokenMatchVal'=>$tokenMatchVal);
        }
        catch(PDOException $ex){
            echo $ex;
        }  
        return $sessionTokenData;
    }

    // Check is current session token matches the token currently active and set in the database. 
    function checkCurrentSession($DBToken, $sessionToken) {
        if (($DBToken != $sessionToken) || ($DBToken == null || $sessionToken == null)) {
            $tokenAuthenticated = array ('tokenAuth'=>0,);
            
            //echo json_encode('User Token does not match DB Token!');

            return $tokenAuthenticated;
        }
        else {
            $tokenAuthenticated = array ('tokenAuth'=>1,);
            
            //echo json_encode('User Token matches DB Token');

            return $tokenAuthenticated;
        }  
    }    
}
